### ISSUE TITLE
What is the reason for using negative examples?

### ISSUE THREAD

**Issue by mahsa1363** [DirtyHarryLYL/Transferable-Interactiveness-Network#57]
Hello
Negative samples have wrong relationships. Therefore minimizing loss does not mean the predictions for these negative samples tend to the wrong relations?What is the reason for using negative examples?

**Comment by Foruck** [comment]
Negative samples are not 'wrong' samples. Instead, they are samples that belong to the 'no interaction' categories. Since the original dataset provides a limited annotation for 'no interaction' samples, with these addition negative samples, we can boost our model's ability to distinguish the difference between samples with interaction and without interaction, in other words, with 'no interaction'.

**Comment by mahsa1363** [comment]
thank you for your answer
Tاhis means, all HOI classes in negative samples are 'no interaction'  which related to specified object?

**Comment by Foruck** [comment]
Yes, that is correct.

**Comment by mahsa1363** [comment]
thank you very much
