### ISSUE TITLE
Some question about the implementation

### ISSUE THREAD

**Issue by karenyun** [DirtyHarryLYL/Transferable-Interactiveness-Network#9]
Hi, @DirtyHarryLYL , thanks for the great work!
I roughly browse the code and have some questions, could you give me some advice!

In the VCOCO model:
1) what the difference between the GT[i][1] and GT[i][4]
2) I cannot understand why the implementation of the function 'binary_discriminator', why 
    the 'fc8_binary_2' only contains the 'positive' human features
3) it seems that you do not compute the 'object_roles' classification, but VCOCO has the 
    GT for 'object roles'.
4) and why you set the action numbers to 29?
5) when you do the evaluation, as there are many human-object combinations even if you 
     have removed some by the interactiveness, will you put these negative samples to the 
     results to compute the mAP or just find the best combination which has the highest 
     action score? (I am confused about the evaluation, will the negative samples influence 
     the mAP)

Thanks very much! Looking forward to your reply!

**Comment by HuangOwen** [comment]
Hi @karenyun , Thanks for your attention.
1.GT[i][1] only contains H-O action while GT[i][4] include more action w/o objects like stand/run/smile. GT[i][1] is a subset of GT[i][4].
2. There are much more negative features than positive features which may bring about difficulties in learning. We use pos only because it has better effect.
3/4. Action index is set to 29 correspondings to the VCOCO settings which are shown in Data/action_index.json (you can download it via Download_data.py). We evaluate our detection result with Average Role AP and Average Agent AP.
5. Those non-interactive HO pairs filtered by interactiveness is not 'removed' but will be given a score of zero, you can see it in tools/Vcoco_lis_nis.py line 251-252.

**Comment by karenyun** [comment]
Hi @HuangOwen Thanks for the quick reply!

2) 
you use the 'fc9_binary' which concatenate the 'fc8_binary_1' and 'fc8_binary_2' to do the binary classification, while the 'fc8_binary_2' only contains the positive human features, do you mean you only use positive human-object pairs to do the binary classification loss? I am confused about it.
(In my understanding, the positive human-object pairs are those who have interaction; negative pairs maybe those wrong combinations) Whether I misunderstand? (If the human has interaction but with the wrong object, is it the negative sample?)

5) Before computing the AP, will you put those non-interactive HO pairs to the results or only put those positive pairs(score>threshold)
(我的意思是假设M是没有经过NIS filtered的HO pairs总数，然后经过NIS可能留下N个组合，你们是拿着N个组合去算AP还是说只拿N个组合中的score大于threshold的pair去算AP)(sorry for my unprofessional)

6) 不好意思我要弃疗打中文了
就是detector会生成很多human、object proposals，比如H1 和 O2是不存在interaction的，那么这个pair在第一个stream里面就算是negative sample，但是H1 可能和O1是存在interaction或者它本身具有某个action，那么在第二个stream中进行HOI classification的时候这个H1还是算是positive(GT不为全0)，O2算negative，他们的sp也算negative？不知道这样理解有没有问题?

7) Are the 'H_weight', 'HO_weight' and 'binary_weight' used for the unbalance？
8) What's the function of the 'mask_HO/H/sp'?

**Comment by HuangOwen** [comment]
2. Yes, we only use positive features to update loss. As I have mentioned, this is because of negative samples are much more than positives. (And  actually, we use it because it **simply has a better score** : ) ). I think your understanding of pos and neg is partly correct. In training, positive examples are given by the dataset. To obtain negative examples:
1> Detect all objects in an image
2> Pair all the Human and Object that has the score higher than a threshold
3> HO pairs that are not included in the GT, are the negative examples

5. We do not remove those pairs when computing AP, NIS only changes the score and as the name suggests "suppress" them. Its implementation is a little bit different in HICO and VCOCO. In VCOCO we only pick those combinations which are in the threshold to compute mAP.
很抱歉之前的回复可能会误导你，按照你的说法的话，对于N个pair里面这些大于non-inter上界或者小于inter下界的（满足NIS条件的）就会不用来计算AP.

6. Pos and Neg are for pair rather than for object/human. Figure2 in our paper may give you a better intuition.  If the human is the same while object changes, the pair can transform from pos to neg.
我们通常不会说一个human或者一个object是positive还是negative，因为训练是以pair为单位的，在你说的例子里面，第一个pair是pos，第二个是neg.

7. Yes, one of the key-problem of HOI detection is the long-tail distribution of a dataset. To tackle this problem we add weight to every category. You can follow our new work [HAKE](http://hake-mvig.cn/home/) which also talks about this problem.

8.mask_HO/H is just a mask label to tell you whether an action is with an object or not (hold-sth is labeled with 1 and smile is labeled with 0). You can see it in ult.py line 664-666

**Comment by karenyun** [comment]
Hi @HuangOwen many thanks 😂!
2. The negative examples you listed also include the single object? learned~

4. Can I give an example of the HO pair as the input to the network?
    The pair H1 and O2 as the input(same as the above I mentioned, H1/O1 is the positive pair), this 
    pair is negative for the first stream. So now you do not compute the binary classification loss for 
    this sample.
    But this pair will also as the input to the second stream to do the HOI classification? (H1 may have 
    one action with O1, while O2 may no interaction with any human, so HO gt for O2 is a zero vector 
    whose length is 29)(这里O2也会去计算HOI loss吗？它在这个情况下是没有任何interaction的)

8. 可以说mask_HO/H/sp是用来filter掉一些错误的分类，我看loss的计算中有乘这个mask，然后在'Vcoco_lis_nis.py'中也有把prediction✖️这个mask。但是为什么要使用apply_prior，这个相当于人为的的也filter掉一些可能错误的组合，是吗？

**Comment by HuangOwen** [comment]
@karenyun Your question is good and I'm glad I could help
4. I'm not sure what you mean by the first/second stream. In our network we have human/object/sp-pose stream for **P** and human/object/sp stream for **C**. In your example, O2 will be included in the loss computation. The network will be penalized via loss if the network gives a prediction of H1-O2 with interaction.
5. In Vcoco_lis_nis we do not multiply prediction with **mask_H/O/sp**, we multiply with **prior_mask** instead. Those two masks are not the same. The first one indicates whether an action is followed by an object or not, we use it for training. And the second one you can see it in Vcoco_lis_nis (line 52-116), its logic is to filter out certain actions (give zero score) considering the object id.

**Comment by karenyun** [comment]
Hi @HuangOwen, thanks~~~
4. Ha, The first stream is to do the binary classification and the second stream is to do the HOI-classification. I got your idea now!

5. Can I ask another question? 
    1) Why do you want to use mask_H/O/sp? Are they good for the training?
    2) And why do you use the prior_mask before computing the mAP? I think maybe we can use a 
        threshold score that can filter out those impossible combinations, do you have tried it?

**Comment by HuangOwen** [comment]
@karenyun 
5.i I go through our codes and actually we do not use mask_H/O/sp anywhere. We intended to use it and in the later version, we delete the codes.  You can just skip them.
5.ii You're right and we have tried the threshold filter but it turns out the final AP is lower than w/o threshold filter. Prior_mask is built on **knowledge** like 'not a book, then the action is impossible to be read'. This knowledge is 100% correct. Adding score threshold is useless and even will cause a worse effect if our detection score is not accurate enough.

**Comment by karenyun** [comment]
@HuangOwen 
5.i please see the line437~443 in 'TIN_VCOCO.py', you use them in the loss???
5.ii I got it, thansk~~~

**Comment by HuangOwen** [comment]
@karenyun Sorry for my mistake, you are right, we multiply them with our cls_score because we do not want certain action contributes to the gradient. In other words, we do not want those action w/o object to influence our model since our model concentrate on Human-Object Interaction. They are good for training.
If you still have problems you can contact me via email.

**Comment by karenyun** [comment]
Many thanks for your sharing and kindness~~

**Comment by karenyun** [comment]
Hi @HuangOwen, it seems that email is not quick can get your reply :)
I still have some questions:
In VO-COCO:
1) Since you have done the data argument for the human and object, so I am wondering the weight that used for the unbalance is based on the original statistic or the new argument dataset?

2) Last time I asked about whether the negative pair samples contribute the binary_classification loss, after reading the code carefully, I found that 
    i) the pos+neg HO pairs all compute the binary loss; 
    ii) the pos+neg HO sp compute the HOI classification loss; 
    iii) you only provide pos human/object features for human and object stream respectively, thus there are no negative human/object samples to do the HOI loss. 
Could you give me some advice about ii) and iii), why?(可能有点钻牛角尖😂)

3) 在VCOCO中存在图片中没有object，即使在GT中也没有，你们是怎么解决这个问题的呢？我感觉你们是直接使用GT的box生成训练数据的？
4) I download the GT for VCOCO, there is no GT for the pose??
